"""Export the measured data the hand-drawn film traces, from ../cache/analysis.npz -> data.js.
Nails = seed 0's W_E(t) projected onto the final (cos, sin) plane of key frequency k = 36, centred and scaled
to unit RMS radius per checkpoint (declared, same as render_film.py).  Also the measured losses, test accuracy,
ring order parameter R and the declared phase boundaries from phases.py."""
import json, sys
import numpy as np
sys.path.insert(0, "..")
from phases import phases
from styles import normalize

SEED, KEY = 0, 36
A = dict(np.load("../cache/analysis.npz"))
j = int(np.where(A["keys"][SEED] == KEY)[0][0])
steps = A["emb_steps"]
ph = phases(A, SEED)

# declared checkpoint selection: sparse on the plateau, dense through cleanup
def keep(t):
    if t <= 1000: return t % 50 == 0
    if t < 19000: return t % 500 == 0
    if t <= 27000: return t % 40 == 0
    return t % 500 == 0
sel = [i for i, t in enumerate(steps) if keep(int(t))]
ring = np.stack([normalize(A["ring"][i, SEED, j].astype(np.float64)) for i in sel])

ev = A["ev_steps"]
cs = np.unique(np.concatenate([np.arange(0, 1000, 10), np.arange(1000, 40001, 100)]))
ci = np.searchsorted(ev, cs)
out = dict(
    seed=SEED, key=KEY, P=int(A["P"]), phases=ph,
    steps=[int(steps[i]) for i in sel],
    ring=np.round(ring, 3).reshape(len(sel), -1).tolist(),
    R=np.round(A["R"][sel, SEED, j], 4).tolist(),
    curve_steps=cs.tolist(),
    train_loss=[float(f"{v:.3e}") for v in np.maximum(A["tr_loss"][cs, SEED], 1e-12)],
    test_loss=[float(f"{v:.3e}") for v in A["te_loss"][ci, SEED]],
    test_acc=np.round(A["te_acc"][ci, SEED].astype(float), 4).tolist(),
)
with open("data.js", "w") as f:
    f.write("// generated by export_data.py from measured training runs; do not edit\n")
    f.write("const GROK = " + json.dumps(out, separators=(",", ":")) + ";\n")
print(len(sel), "checkpoints", ph)
