"""Export small data files for the widgets (loaded via <script>, works from file://).

    python export_widgets.py   -> widgets/data_rf.js, widgets/data_risk.js
"""
import json, pathlib
import numpy as np

import compute_hero as H
import dd_core as C

HERE = pathlib.Path(__file__).resolve().parent
W = HERE / "widgets"; W.mkdir(exist_ok=True)


def r(a, d=6):
    return [float(f"{v:.{d}g}") for v in np.asarray(a).ravel()]


def main():
    z = np.load(HERE / "cache" / "hero.npz")
    Ps = z["Ps"]; keep = Ps <= 400
    rep = int(z["rep"])
    Wf, Bf = H.features(1000 + rep)
    x, y = z["x"], z["y"]
    # reference values for the widget self-test: min-norm and ridge risks with the exported features
    xs = np.linspace(-1, 1, 301); fs = H.target(xs)
    ref = []
    for P in [5, 12, 19, 20, 21, 40, 150, 400]:
        for lam in [0.0, 1e-3]:
            a = H.fit(x, y, Wf, Bf, P, lam)
            ref.append(dict(P=P, lam=lam, risk=float(np.mean((H.phi(xs, Wf, Bf, P) @ a - fs) ** 2)),
                            smin=float(np.linalg.svd(H.phi(x, Wf, Bf, P), compute_uv=False)[-1])))
    data = dict(x=r(x, 10), y=r(y, 10), W=r(Wf[:400], 12), B=r(Bf[:400], 12), scale=H.SCALE, noise=H.NOISE,
                Ps=[int(p) for p in Ps[keep]], med=r(np.median(z["R"], 1)[keep], 4),
                q1=r(np.percentile(z["R"], 25, axis=1)[keep], 4), q3=r(np.percentile(z["R"], 75, axis=1)[keep], 4),
                selftest=ref)
    (W / "data_rf.js").write_text("// generated by export_widgets.py\nwindow.RF_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
    # reference values for the closed-form risk widget self-test
    ref2 = []
    for g in [0.3, 0.9, 1.5, 4.0]:
        for snr in [1.0, 5.0]:
            for lam in [0.0, 0.01, 0.5]:
                if lam == 0:
                    R, B, V = C.ridgeless_risk(g, snr, 1.0)
                else:
                    R, B, V = C.ridge_risk(g, lam, snr, 1.0)
                ref2.append(dict(g=g, snr=snr, lam=lam, R=float(R), B=float(B), V=float(V)))
    (W / "data_risk.js").write_text("// generated by export_widgets.py\nwindow.RISK_REF = " + json.dumps(ref2) + ";\n")
    print("wrote", W / "data_rf.js", (W / "data_rf.js").stat().st_size, "bytes")
    for q in ref:
        print(q)


if __name__ == "__main__":
    main()
